# Generated by Django 2.0 on 2017-12-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='post', unique=True),
            preserve_default=False,
        ),
    ]
