# Generated by Django 2.0 on 2017-12-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20171219_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='description', max_length=120),
            preserve_default=False,
        ),
    ]
