# Generated by Django 2.0 on 2017-12-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20171221_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default='Leave your comment', max_length=150),
            preserve_default=False,
        ),
    ]
